version: "3.1"

services:
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: flask
      MYSQL_DATABASE: flask

  back-end:
    build: back-end/.
    restart: always
    ports:
      - 81:3000
    depends_on:
      - database
    command: ./start.sh

  front-end:
    build: ./front-end/.
    restart: always
    ports:
      - 80:3000
    command: npm start run
